### PR TITLE
Make search case-insensitive for all SQL drivers

### PR DESCRIPTION
**Pull request by mikebronner**
Have you had any issues trying this approach? Would be nice to have search be case-insensitive for all drivers. :)

### CODE REVIEW

**Comment by fede91it** [comment]
No way to get this merged I think... I did the same request months ago and my fork was not merged

**Comment by TitasGailius** [comment]
I'll take a look at this today.

I don't want the search to become somehow different from how the default Laravel Nova search works. If this keeps the same behaviour I'll merge it.

**Comment by fede91it** [comment]
It is the same behaviour but case insensitive


--
Federico Liva Full Stack Web Developer


Phone: (+39) 340 768 2386 Skype: federico.liva On Tue, Nov 19, 2019 at 10:46am, Titas Gailius < notifications@github.com [notifications@github.com] > wrote:
I'll take a look at this today.

I don't want the search to become somehow different from how the default Laravel Nova search works. If this keeps the same behaviour I'll merge it.

**Comment by TitasGailius** [comment]
I finally got some time to check this. I want the relationship search to behave **exactly the same** how Nova is behaving with regular search. This PR breaks this consistency.

 If you want to adjust the behaviour to your needs, overriding this method is not of a big deal.

**Pull request closed without merging**
