### PR TITLE
Added Morphto Relationship

### PR DESCRIPTION
**Pull request by thisisablock**

### CODE REVIEW

**Comment by TitasGailius** [comment]
Good work! It looks really promising, I'll check it later this week.

**Comment by TitasGailius** [comment]
I plan to release https://github.com/TitasGailius/nova-search-relations/pull/27 soon.

Then, a morphable search could simply be something like a custom `MorphSearch` class.

**Comment by TitasGailius** [comment]
Another thing I don't necessarily agree with is that you pull all types from the database.

It would fail if we had a `commentable` relationship that could either be a `Post` or a `Video` and one of those model tables didn't have some of the specified fields:


```php
/**
 * The relationship columns that should be searched.
 *
 * @var array
 */
public static $searchRelations = [
    'commentable' => ['post_title', 'video_description'],
];
```

Now if `commentable` can either be a `Video` or a `

**Comment by TitasGailius** [comment]
I merged #27. Now you have full control on how the search works and you may even extend the search capabilities with your own logic.

Regarding morphable search, I'll check it this/next week.

**Comment by thisisablock** [comment]
@TitasGailius thanks :)

**Comment by 970Design** [comment]
@TitasGailius thanks for adding this feature!

One issue I'm running into while using the master branch after this feature has been added is that `ensureRelationshipExists` in `RelationSearch` always fails on nested relationships when applying the search.  

I'm unfortunately not sure why though.. the same queries work just fine on the tagged version 1.0.6

**Comment by asivaneswaran** [comment]
@TitasGailius 
What if I have a nester relation? Let's say I have something like:

`commentable(Video or Photo).someModel`

And I want to search fields in from `someModel`?

**Comment by anditsung** [comment]
> @TitasGailius What if I have a nester relation? Let's say I have something like:
> 
> `commentable(Video or Photo).someModel`
> 
> And I want to search fields in from `someModel`?

example

Action Resource
```php
public static function searchableRelations(): array
    {
        return [
            'target' => new MorphSearch([
                'App\Models\Role' => ['name'],
                'App\Models\User' => [
                    'name',
                    'username',
                    'email',
                    'roles' => ['name']
                ],
                'App\Models\Permission' => ['name'],
                'App\Models\Invite' => [
                    'email',
                    'role' => ['name']
                ],
            ])
        ];
    }
```

MorphSearch class
```php
class MorphSearch implements Search
{
    /**
     * Searchable columns.
     *
     * @var array
     */
    protected $morphRelation;


    protected $fallbackClass = '*';

    protected $fallbackColumns = [
        'id'
    ];

    /**
     * Instantiate a new search query instance.
     *
     * @param array $columns
     */
    public function __construct(array $morphRelation)
    {
        $this->morphRelation = $morphRelation;
    }

    public function apply(Builder $query, string $relation, string $search): Builder
    {
        foreach ($this->morphRelation as $morphClass => $columns) {
            if (class_exists($morphClass) && is_subclass_of($morphClass, Model::class)) {
                $query->orWhereHasMorph($relation, [$morphClass], function ($query) use ($columns, $relation, $search) {
                    [$columnSearch, $relationSearch] = $this->parseColumns($columns);

                    (new ColumnSearch($columnSearch->toArray()))->apply($query, $relation, $search);

                    foreach ($relationSearch as $relationName => $relationsColumns) {
                        (new RelationSearch($relationsColumns))->apply($query, $relationName, $search);
                    }
                });
            }
        }

        // search all morph class with default columns
        $query->orWhereHasMorph($relation, $this->fallbackClass, function ($query) use ($relation, $search) {
            return (new ColumnSearch($this->fallbackColumns))->apply($query, $relation, $search);
        });

        return $query;
    }

    private function parseColumns($columns): array
    {
        $columns = collect($columns);

        $columnSearch = $columns->filter(function ($value, $key) {
            return is_numeric($key);
        });

        $relationSearch = $columns->filter(function ($value, $key) {
            return is_string($key);
        });

        return [$columnSearch, $relationSearch];
    }
}
```

**Pull request closed without merging**
