### PR TITLE
Fix to qualify columns and use connectionType like operator.

### PR DESCRIPTION
**Pull request by anderly**
Based on Laravel\Nova\PerformsQueries trait.

### CODE REVIEW

**Comment by anderly** [comment]
FYI, this is needed in case you have the same column names (i.e. `name`, `description`) in the tables being joined. Let me know if you have any questions and if you can merge.

**Comment by TitasGailius** [comment]
I'll check this tomorrow

**Comment by TitasGailius** [comment]
Thanks for your contribution. I'll release it soon.

**Comment by anderly** [comment]
@TitasGailius just checking to see if you can publish a release with this change?

**Pull request merged**
